"""empty message

Revision ID: 20eca2764f0
Revises: 4434d879c71
Create Date: 2015-10-25 17:19:48.730178

"""

# revision identifiers, used by Alembic.
revision = '20eca2764f0'
down_revision = '4434d879c71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('pizza_ordering_is_allowed', sa.BOOLEAN(), nullable=True),
    sa.Column('ordered_pizzas', sa.BLOB(), nullable=True),
    sa.Column('users_already_ordered', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('who_created', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
