"""empty message

Revision ID: 4dab1a5013a
Revises: 1983556ef83
Create Date: 2015-06-24 17:57:06.480223

"""

# revision identifiers, used by Alembic.
revision = '4dab1a5013a'
down_revision = '1983556ef83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_user', sa.String(length=100), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.Column('food_type', sa.String(length=30), nullable=True),
    sa.Column('other_food_type', sa.String(length=60), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('food_company', sa.String(length=50), nullable=True),
    sa.Column('menu', sa.String(length=500), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('deadline_for_ordering', sa.DateTime(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('users', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foodevent')
    ### end Alembic commands ###
