"""empty message

Revision ID: 54c994cff69
Revises: 51afbfc4c54
Create Date: 2015-02-05 16:11:04.474970

"""

# revision identifiers, used by Alembic.
revision = '54c994cff69'
down_revision = '51afbfc4c54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
