"""empty message

Revision ID: 569f34ded75
Revises: None
Create Date: 2015-01-26 15:50:27.442332

"""

# revision identifiers, used by Alembic.
revision = '569f34ded75'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('o_type', sa.String(length=100), nullable=True))
    op.drop_column('order', 'meal_from_list')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('meal_from_list', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('food', 'o_type')
    ### end Alembic commands ###
